// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package data

import (
	"database/sql"
	"time"
)

type Pdf struct {
	ID         int64        `json:"id"`
	Uuid       string       `json:"uuid"`
	UserID     int64        `json:"user_id"`
	Name       string       `json:"name"`
	CreatedAt  sql.NullTime `json:"created_at"`
	LastOpenAt sql.NullTime `json:"last_open_at"`
}

type Session struct {
	ID                int64        `json:"id"`
	UserID            int64        `json:"user_id"`
	Email             string       `json:"email"`
	Expiry            time.Time    `json:"expiry"`
	Token             string       `json:"token"`
	ActivateCode      string       `json:"activate_code"`
	RefreshToken      string       `json:"refresh_token"`
	UserIp            string       `json:"user_ip"`
	Type              string       `json:"type"`
	PostSuspendExpiry sql.NullTime `json:"post_suspend_expiry"`
	IsExpired         sql.NullBool `json:"is_expired"`
}

type User struct {
	ID         int64          `json:"id"`
	Uuid       string         `json:"uuid"`
	Name       string         `json:"name"`
	Email      sql.NullString `json:"email"`
	FolderUuid string         `json:"folder_uuid"`
	IsDraft    bool           `json:"is_draft"`
	CreatedAt  sql.NullTime   `json:"created_at"`
}
